title: thewittyswan
description: "Notes on networks, security, and literature."
url: "https://thewittyswan.space"
baseurl: ""

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"